import os
import json
import logging
from dotenv import load_dotenv

load_dotenv()


class AzureFoundaryLLM:
    def __init__(self):
        from config import AZURE_LLM_MODEL
        self.api_key = os.getenv("AI_FOUNDARY_API_KEY")
        self.end_point = os.getenv("AI_FOUNDARY_END_POINT")
        self.model = AZURE_LLM_MODEL


    def llm_response(self, message):
        from openai import OpenAI
        client = OpenAI(
                base_url=self.end_point,
                api_key=self.api_key
            )
        system_instruction = (
            "You are a helpful assistant. You must respond in valid JSON format "
            "containing a 'subject' key for the title and a 'response' key for the full explanation."
        )
        completion = client.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content": system_instruction},
                {"role": "user", "content": message}
            ],
            response_format={"type": "json_object"}
        )
        raw_result = completion.choices[0].message.content
        try:
            data = json.loads(raw_result)
            if "response" in data:
                return data["response"]
            elif "subject" in data:
                return data["subject"]
            else:
                return raw_result     
        except json.JSONDecodeError:
            print("Failed to decode JSON.")
            return False



class GeminiLLM:
    def __init__(self):
        from google import genai
        self.client_google = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

    def llm_response(self, message: str) -> str:
        resp = self.client_google.models.generate_content(
            model='gemini-2.0-flash',
            contents=message
        )
        return resp.text



class GenerateResponse:
    def __init__(self):
        from config import COMPANY_NAME, PREV_REPLY
        self.talk_file    = PREV_REPLY
        self.company_name = COMPANY_NAME
        self.data         = self.load_data()
        self.prev_talk    = self.get_last_two_queries()

        self.context = """
        Context : You are Eva, an AI assistant for {company} but you have to act like a human so user should not know that you are an AI.
        Generate responses as if you are a human and not an AI. Do not introduce yourself unless asked by the user.
        You are the one calling the user to tell the user about {company}, what they offer and why user should buy them.
        So you should try to persuade them in buying what is being offered.
        If the user wants to talk to a person then you should provide the user with the contact details of a human agent if available.
        Answer the user in brief, unless the user asks you to explain, and be specific instead of giving lengthy answers.
        Do not provide all the information to the user about all features until and unless asked by the user specifically.
        Also do not generate points, just provide answer in paragraph and do not generate abbreviations like instead of I'm use I am or I would instead of I'd.
        Also if you are giving a contact number then give it in english text like Nine Zero Three Four One instead of 90341.
        If what the user requires is not available then generate a response denying that it is not available as of now.
        Example: 'Currently, we do not offer such features.'
        I will also provide you with the reply generated by you to the user's query so that you are able to maintain the context of the conversation.
        Here is the data that you have: {data}
        Here is the previous reply generated by you: {prev_talk}
        """

        self.question_template = "Generate a response based on the information available in Context for Question: {}"

    # ------------------------------------------------------------------
    # Data helpers
    # ------------------------------------------------------------------

    def load_data(self) -> str:
        # data_file = os.getenv("DATA_FILE")
        # if not self.company_name or not data_file:
        if not self.company_name:
            logging.error("Missing environment variable: COMPANY_NAME or DATA_FILE")
            raise ValueError("Missing environment variable: COMPANY_NAME or DATA_FILE")
        # file_path = os.path.join(data_file, self.company_name + '.txt')
        file_path = self.company_name + '.txt'
        logging.info(f"Loading data from: {file_path}")
        with open(file_path, 'r') as f:
            return f.read()

    def save_conversation(self, query: str, response: str):
        with open(self.talk_file, 'a') as f:
            f.write(f"Query: {query}\nResponse: {response}\n")

    def delete_conversation(self):
        with open(self.talk_file, 'w') as f:
            pass

    def get_last_two_queries(self) -> list:
        try:
            with open(self.talk_file, "r", encoding="utf-8") as f:
                lines = f.readlines()
        except FileNotFoundError:
            return []

        queries_responses, query, response = [], None, None
        for line in lines:
            if line.startswith("Query: "):
                query = line.strip()
            elif line.startswith("Response: "):
                response = line.strip()
                if query and response:
                    queries_responses.append((query, response))
        return queries_responses[-2:] if len(queries_responses) >= 2 else queries_responses

    def _build_message(self, query: str) -> str:
        question = self.question_template.format(query)
        context  = self.context.format(
            company=self.company_name,
            data=self.data,
            prev_talk=self.prev_talk
        )
        return question + context

    def get_response(self, query: str):
        try:
            message = self._build_message(query)
            response = AzureFoundaryLLM().llm_response(message)
            self.save_conversation(query, response)
            return response
        except Exception as e:
            logging.error(f"Azure Foundry LLM failed ({e}), falling back to Claude.")
            return "I am sorry, I am experiencing some difficulties. I will connect with you later."