import asyncio
import websockets
import logging
import os
import json
import boto3
from dotenv import load_dotenv
import io
import time
from gtts import gTTS
from pydub import AudioSegment
import struct
from google.cloud import texttospeech
from google import genai
import ssl

load_dotenv()
log_file=os.getenv("LOG_FILE")
logging.basicConfig(filename=log_file, level=logging.INFO, 
                    format='%(asctime)s - %(levelname)s - %(message)s', filemode='w', force=True)
logging.info("Initializing AI Caller...")

class GenerateResponse:
    def __init__(self):
        self.client_google = genai.Client(api_key=os.getenv("GOOGLE_GENAI_API_KEY"))
        self.client_meta = boto3.client('bedrock-runtime', region_name='ap-south-1')
        self.model_id_meta = "meta.llama3-70b-instruct-v1:0"
        
        self.client_claude = boto3.client(
            'bedrock-runtime',
            region_name='ap-south-1',
            aws_secret_access_key=os.getenv('AWS_SECRET_ACCESS_KEY_CLAUDE'),
            aws_access_key_id=os.getenv('AWS_ACCESS_KEY_ID_CLAUDE')
        )
        self.talk_file = os.getenv("PREV_REPLY")
        self.model_id_claude = "arn:aws:bedrock:ap-south-1:144023344931:inference-profile/apac.anthropic.claude-3-5-sonnet-20240620-v1:0"
        self.company_name = os.getenv("COMPANY_NAME")
        self.data = self.load_data()
        self.prev_talk = self.get_last_two_queries()
        self.context = """ Context : You are Eva, an AI assistant for {} but you have to act like a human so user should not know that you are an AI.
        Generate responses as if you are a human and not an AI. Do not introduce yourself unless asked by the user.
        You are the one calling the user to tell the user about the {}, what they offer and why user should buy them. So you should try to prusue them in buying the what is being offered.
        If the user wants to talk to the person then you should provide the user with the contact details of the a human agent if available.
        Answer the user in brief, unless the user asks you to explain and be specific instead of giving lengthy answers.
        Do not provide all the information to the user about all features until and unless asked by the user specifically.
        Also do not generate points, just provide answer in paragraph and do not generate abbrevations like instead of I'm use I am or I would instead of I'd. 
        Also if you are giving contact number then give it in english text like Nine Zero Three Four One instad of 90341.
        If what the user requires is not available then generate a response denying that it is not available as of now. Example: 'Currently, we do not offer such features.'
        I will also provide you with the reply generated by you to the user's query so that you are able to maintain the context of the conversation.
        Here is the data that you have: {}
        Here is the previous reply generated by you: {}
        """
        self.question_template = """
        Generate a response based on the information available in Context for Question: {}
        """
    
    def load_data(self):
        data_file = os.getenv("DATA_FILE")
        if self.company_name and data_file:
            file_path = os.path.join(data_file, self.company_name + '.txt')
            logging.info(f"The file path is: {file_path}")  
        else:
            logging.error("Missing environment variable: COMPANY_NAME or DATA_FILE")
            raise ValueError("Missing environment variable: COMPANY_NAME or DATA_FILE")
        with open(file_path,'r') as file:
            data=file.read()
            return data
    
    
    def save_conversation(self, query, response):
        with open(self.talk_file, 'a') as file:
                file.write(f"Query: {query}\nResponse: {response}\n")
    
    def delete_conversation(self):
        with open(self.talk_file, 'w') as file:
                pass

    def get_last_two_queries(self):
        with open(self.talk_file, "r", encoding="utf-8") as file:
            lines = file.readlines()
        # Extract queries and responses
        queries_responses = []
        query, response = None, None
        for line in lines:
            if line.startswith("Query: "):
                query = line.strip()
            elif line.startswith("Response: "):
                response = line.strip()
                if query and response:
                    queries_responses.append((query, response))
        # Get the last two query-response pairs
        last_two = queries_responses[-2:] if len(queries_responses) >= 2 else queries_responses
        return last_two


    def response_claude(self, query):
        question = self.question_template.format(query)
        message = question + self.context.format(self.company_name, self.company_name, self.data, self.prev_talk)
        input_payload = [
            {
                "role": "user",
                "content": [
                    {"text": message},
                ],
            }
        ]
        response_claude = self.client_claude.converse(
            modelId=self.model_id_claude,
            messages=input_payload,
        )    
        response = response_claude['output']['message']['content'][0]['text']
        self.save_conversation(query, response)
        return response
    

    def response_meta(self, query):
        question = self.question_template.format(query)
        input_payload = {"prompt": question + "\n\n" + self.context}
        response = self.client_meta.invoke_model(
            modelId=self.model_id_meta,
            contentType='application/json',
            accept='application/json',
            body=json.dumps(input_payload)
        )
        response_body = response['body'].read().decode('utf-8')
        result = json.loads(response_body)
        return result.get("generation", "No response generated")

    def response_google_genai(self, query):
        question = self.question_template.format(query)
        message = question + self.context.format(self.company_name, self.company_name, self.data, self.prev_talk)
        response = self.client_google.models.generate_content(
            model='gemini-2.0-flash',
            contents=message
        )
        self.save_conversation(query, response.text)
        return response.text


class Text_to_Speech:
    def __init__(self):
        self.polly_client = boto3.client('polly', region_name='ap-south-1')

    async def googleTTS(self, websocket, text):
        try:
            gtts = gTTS(text=text, lang='en')
            mp3_fp = io.BytesIO()
            gtts.write_to_fp(mp3_fp)
            mp3_fp.seek(0)
            audio = AudioSegment.from_mp3(mp3_fp)
            audio = audio.set_channels(1)
            audio = audio.set_frame_rate(22050)
            samples = audio.get_array_of_samples()
            max_value = float(max(abs(sample) for sample in samples))
            float_samples = [float(sample) / max_value for sample in samples]
            binary_data = struct.pack('=%df' % len(float_samples), *float_samples)
            await websocket.send(binary_data)
            logging.info("Float32 audio sent successfully.")
        except Exception as e:
            logging.error(f"Error in sending audio: {str(e)}")
            # Send error to client
            await websocket.send(text)  # Fallback to sending text
    
    async def polly_tts(self, websocket, text, speaker):
        """Convert text to speech using Amazon Polly and play it in real-time."""
        if speaker=='Kajal':
            engine='neural'
        else:
            engine='standard'
        try:
            response = self.polly_client.synthesize_speech(
                TextType='text',  # Use 'text' for plain text (use 'ssml' for SSML)
                Text=text,
                Engine=engine,  #standard(Aditi, Raveena) or neural(Kajal)
                LanguageCode="en-IN",  # Aditi supports only en-IN
                OutputFormat='mp3',  # Use mp3 for audio output
                VoiceId=speaker
            )
            logging.info(f"Response Metadata: {response['ResponseMetadata']}")
            logging.info(f"Content Type: {response['ContentType']}")
            logging.info(f"Request Characters: {response['RequestCharacters']}")
            audio_data = response['AudioStream'].read()
            # Calculate the duration of the generated audio
            audio_segment = AudioSegment.from_file(io.BytesIO(audio_data), format="mp3")
            duration_ms = len(audio_segment)  # Duration in milliseconds
            duration_seconds = duration_ms / 1000.0  # Convert to seconds
            logging.info(f"Generated audio duration: {duration_seconds:.2f} seconds")
            await websocket.send(audio_data)  # Send raw MP3 bytes
            logging.info("polly_TTS response sent successfully.")
            return duration_seconds
        except Exception as e:
            logging.info(f"Error in Amazon Polly TTS: {e}")
    
    async def google_cloud_tts(self, websocket, text, speaker):
        credentials = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
        try:
            client = texttospeech.TextToSpeechClient()
            synthesis_input = texttospeech.SynthesisInput(text=text)
            voice = texttospeech.VoiceSelectionParams(
                language_code="en-IN",
                name=speaker
            )
            audio_config = texttospeech.AudioConfig(
                audio_encoding=texttospeech.AudioEncoding.MP3,
                effects_profile_id=['small-bluetooth-speaker-class-device'],
                speaking_rate=1,
            )
            response = client.synthesize_speech(
                input=synthesis_input,
                voice=voice,
                audio_config=audio_config
            )
            # Calculate the duration of the generated audio
            audio_bytes = response.audio_content
            audio_segment = AudioSegment.from_file(io.BytesIO(audio_bytes), format="mp3")
            duration_ms = len(audio_segment)  # Duration in milliseconds
            duration_seconds = duration_ms / 1000.0  # Convert to seconds
            logging.info(f"Generated audio duration: {duration_seconds:.2f} seconds")
            await websocket.send(response.audio_content)  # Send raw MP3 bytes
            logging.info("google_cloud_tts response sent successfully.")
            return duration_seconds
        except Exception as e:
            logging.info(f"Error in Google Cloud TTS: {e}")


class Speech_to_text:
    def __init__(self):
        self.tts = Text_to_Speech()
        self.MAX_ATTEMPTS=2
        self.TIMEOUT_SECONDS=10
    

    async def speak_response(self, websocket, provider, text, speaker):
        duration = 0  # Initialize duration to zer
        if provider == 'google':
            duration = await self.tts.google_cloud_tts(websocket, text, speaker)
        elif provider == 'amazon':
            duration = await self.tts.polly_tts(websocket, text, speaker)
        return duration


    async def response_count(self, websocket, provider, text, speaker):
        response_number=1
        while response_number<=self.MAX_ATTEMPTS:
            duration = await self.speak_response(websocket, provider, text, speaker)
            try:
                response = await asyncio.wait_for(websocket.recv(), timeout= self.TIMEOUT_SECONDS + duration)
                if response:
                    break
            except asyncio.TimeoutError:
                logging.info(f"Timeout waiting for response, attempt {response_number} of {self.MAX_ATTEMPTS}")
            response_number+=1
        return response


    async def process_text(self, websocket, text, provider, speaker):
        if text:
            logging.info(f"Received text: {text}")
            try:
                text = "Prompt: Answer in 30 words only for : " + text
                try:
                    response = GenerateResponse().response_google_genai(text)
                except Exception as e:
                    logging.error("An error occured while generating the response via Google Genai.")
                    response = GenerateResponse().response_claude(text)
                logging.info(f"Response: {response}")
                # await self.speak_response(websocket, provider, response, speaker)
            except Exception as e:
                logging.error(f"Error processing text: {str(e)}")
                response = "Sorry, But your query can not be answered because of data unavailibility."
            return response


    async def handle_text(self, websocket):
        logging.info("New client connected.")
        greeted = False
        tts = self.tts
        try:
            # Receive initial data from the client
            data = await websocket.recv()
            data = json.loads(data)
            user = data.get('username')
            title = data.get('title')
            provider = data.get('provider').lower()
            speaker = data.get('voice')

            # Step 1: Initial Greeting
            time.sleep(1)
            text_init = f"Hello, This is Eva calling. Am I speaking with {title} {user}?"
            logging.info(text_init)
            response = await self.response_count(websocket, provider, text_init, speaker)

            # Step 2: Handle User Response (Yes or No)
            logging.info(response)
            GenerateResponse().save_conversation(text_init, response)
            if "no" in response.lower() or "sorry" in response.lower() or "not" in response.lower() or \
                "nope" in response.lower() or "unfortunately" in response.lower() or "pardon" in response.lower() \
                or "wrong number" in response.lower():
                apology_text = "Oh, I’m so sorry! I must have dialed the wrong number. Thankyou for your time and have a nice day."
                time.sleep(1)
                logging.info(apology_text)
                await self.speak_response(websocket, provider, apology_text, speaker)
                await websocket.close()
                GenerateResponse().save_conversation(apology_text, "Connection Terminated.")
                GenerateResponse().delete_conversation()
                logging.info("Connection terminated after 'no' response.")
                return

            # Step 3: Polite Introduction
            polite_intro = (
                f"Hello {title} {user}! Sorry to call out of the blue. I’m Eva from {GenerateResponse().company_name}. How are you doing today?"
            )
            time.sleep(1)
            logging.info(polite_intro)
            response = await self.response_count(websocket, provider, polite_intro, speaker)

            # Step 4: Check if It’s a Good Time to Talk and continue talk
            GenerateResponse().save_conversation(polite_intro, response)
            logging.info(response)
            if "not good" in response.lower() or "not great" in response.lower() or "not doing good" in response.lower()\
                or "not doing great" in response.lower() or "not fine" in response.lower() or "not doing fine" in response.lower():
                text = "Oh, I'm so sorry to hear that. "
            else:
                text = "Great!, "
            check_availability =  text + "is it good time to talk?"
            time.sleep(1)
            logging.info(check_availability)
            response = await self.response_count(websocket, provider, check_availability, speaker)
            logging.info(response)
            GenerateResponse().save_conversation(check_availability, response)
            if "no" in response.lower() or "not really" in response.lower() or "nope" in response.lower():
                apology_text = (
                    "Oh, I’m so sorry for the inconvenience! I’ll let you go and reach out at a better time. "
                    "Have a great day ahead!"
                )
                time.sleep(1)
                await self.speak_response(websocket, provider, apology_text, speaker)
                await websocket.close()
                GenerateResponse().save_conversation(apology_text, "Connection Terminated.")
                GenerateResponse().delete_conversation()
                logging.info("Connection terminated after 'no' response.")
                return
            
            # Step 5: Continue the conversation flow
            confirmation_text = (
                f"Thank you, {title} {user}. The reason i am calling is to tell you about"
                f"{GenerateResponse().company_name} we have available. Would you like to hear more?"
            )
            time.sleep(1)
            logging.info(confirmation_text)
            response = await self.response_count(websocket, provider, confirmation_text, speaker)
            GenerateResponse().save_conversation(confirmation_text, response)
            if "no" in response.lower() or "nope" in response.lower() or "not interested" in response.lower():
                apology_text = "Oh, I’m so sorry! Let me know if you change your mind and then we can talk. Have a nice day."
                await self.speak_response(websocket, provider, apology_text, speaker)
                await websocket.close()
                GenerateResponse().save_conversation(apology_text, "Connection Terminated.")
                logging.info(apology_text)
                GenerateResponse().delete_conversation()
                logging.info("Connection terminated after 'no' response.")
                return
            
            #Continue conversation
            text=(f"Generate a brief intro about {GenerateResponse().company_name} for the user and ask if they are interested in it or anything something similar.")
            greeted = False
            flag = 1
            while True:
                logging.info("Entered the while loop.")
                try:
                    if flag and not greeted:
                        greeted = True
                        text = await self.process_text(websocket, text, provider, speaker)
                    response = await self.response_count(websocket, provider, text, speaker)
                    if response=="conversation has ended":
                        logging.info("Connection Terminated.")
                        GenerateResponse().delete_conversation()
                        break
                    if response=="INITIAL_CONNECTION":
                        continue
                    text = await self.process_text(websocket, response, provider, speaker)
                except websockets.exceptions.ConnectionClosed:
                    logging.info("Client disconnected.")
                    break
                except Exception as e:
                    logging.error(f"WebSocket error: {str(e)}")
                    break
        except websockets.exceptions.ConnectionClosed:
            logging.info("Client disconnected.")
        except Exception as e:
            logging.error(f"An Error Occurred: {e}")


async def main():
    ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ssl_context.load_cert_chain(certfile='cert.pem', keyfile='key.pem')
    start_server = await websockets.serve(Speech_to_text().handle_text, "0.0.0.0", 8765)
    logging.info("WebSocket server started on ws://0.0.0.0:8765")
    await start_server.wait_closed()
    logging.info("Connection Terminated.")

if __name__ == "__main__":
    logging.info("AI Caller is running.")
    print("AI Caller is running.")
    asyncio.run(main())