import asyncio
import websockets
import logging
import numpy as np
from TTS.api import TTS
import re
import os
import json
import boto3
from dotenv import load_dotenv
import io
import pygame
import time
from gtts import gTTS
from pydub import AudioSegment
import struct


load_dotenv()
log_file=os.getenv("LOG_FILE")
logging.basicConfig(filename=log_file, level=logging.INFO, 
                    format='%(asctime)s - %(levelname)s - %(message)s', filemode='w', force=True)
logging.info("Initializing AI Caller...")

tts = TTS(model_name="tts_models/en/ljspeech/vits").to("cpu")
tts2 = TTS("tts_models/multilingual/multi-dataset/xtts_v2").to("cpu")
sample_audio = "/home/ubuntu/ai_caller/sample_audio.wav"
logging.info("TTS model loaded successfully.")
# greeted = False

class GenerateResponse:
    def __init__(self):
        self.client_meta = boto3.client('bedrock-runtime', region_name='ap-south-1')
        self.model_id_meta = "meta.llama3-70b-instruct-v1:0"
        
        self.client_claude = boto3.client(
            'bedrock-runtime',
            region_name='ap-south-1',
            aws_secret_access_key=os.getenv('AWS_SECRET_ACCESS_KEY_CLAUDE'),
            aws_access_key_id=os.getenv('AWS_ACCESS_KEY_ID_CLAUDE')
        )
        self.talk_file = os.getenv("PREV_REPLY")
        self.model_id_claude = "arn:aws:bedrock:ap-south-1:144023344931:inference-profile/apac.anthropic.claude-3-5-sonnet-20240620-v1:0"
        self.data = self.load_data()
        self.prev_talk = self.get_last_two_queries()
        self.context = """ Context : You are Eva, an AI assistant for Duplex Builders but you have to act like a human so user should not know that you are an AI.
        You are the one calling the user to tell the user about the duplex builders, properties available and why user should buy them. So you should try to prusue them in buying the properties.
        If the user wants to talk to the person then you should provide the user with the contact details of the a human agent. The contact number is 9012345678.
        You provide information about properties, prices, locations, and amenities that Duplex Builders sells or rents.
        Answer the user in brief, unless the user asks you to explain and be specific instead of giving lengthy answers.
        Do not provide all the information to the user about the property like amenities and other features until and unless asked by the user specifically.
        Also do not generate points, just provide answer in paragraph and do not generate abbrevations like instead of I'm use I am or I would instead of I'd. 
        Also if you are giving contact number then give it in english text like Nine Zero Three Four One instad of 90341.
        If the property is not available at the location in the provided data
        then you should generate the answer like 'Currently, at this location, they do not have any property.'
        I will also provide you with the reply generated by you to the user's query so that you are able to maintain the context of the conversation.
        Here is the data that you have: {}
        Here is the previous reply generated by you: {}
        """
        self.question_template = """
        Generate a response based on the information available in Context for Question: {}
        """
    
    def load_data(self):
        file_path = os.getenv('DATA_FILE')
        with open(file_path,'r') as file:
            data=file.read()
            return data
    

    def get_last_two_queries(self):
        with open(self.talk_file, "r", encoding="utf-8") as file:
            lines = file.readlines()
        # Extract queries and responses
        queries_responses = []
        query, response = None, None
        for line in lines:
            if line.startswith("Query: "):
                query = line.strip()
            elif line.startswith("Response: "):
                response = line.strip()
                if query and response:
                    queries_responses.append((query, response))
        # Get the last two query-response pairs
        last_two = queries_responses[-2:] if len(queries_responses) >= 2 else queries_responses
        return last_two


    def response_claude(self, query):
        question = self.question_template.format(query)
        message = question + self.context.format(self.data, self.prev_talk)
        input_payload = [
            {
                "role": "user",
                "content": [
                    {"text": message},
                ],
            }
        ]
        response_claude = self.client_claude.converse(
            modelId=self.model_id_claude,
            messages=input_payload,
        )    
        response = response_claude['output']['message']['content'][0]['text']
        with open(self.talk_file, 'a') as file:
                file.write(f"Query: {query}\nResponse: {response}\n")
        return response
    

    def response_meta(self, query):
        question = self.question_template.format(query)
        input_payload = {"prompt": question + "\n\n" + self.context}
        response = self.client_meta.invoke_model(
            modelId=self.model_id_meta,
            contentType='application/json',
            accept='application/json',
            body=json.dumps(input_payload)
        )
        response_body = response['body'].read().decode('utf-8')
        result = json.loads(response_body)
        return result.get("generation", "No response generated")


class Text_to_Speech:
    def __init__(self):
        pass
        # tts = TTS(model_name="tts_models/hi/cv/vits").to("cpu")
        # logging.info("Hindi TTS model loaded successfully.")

    async def googleTTS(self, websocket, text):
        try:
            gtts = gTTS(text=text, lang='en')
            mp3_fp = io.BytesIO()
            gtts.write_to_fp(mp3_fp)
            mp3_fp.seek(0)
            audio = AudioSegment.from_mp3(mp3_fp)
            audio = audio.set_channels(1)
            audio = audio.set_frame_rate(22050)
            samples = audio.get_array_of_samples()
            max_value = float(max(abs(sample) for sample in samples))
            float_samples = [float(sample) / max_value for sample in samples]
            binary_data = struct.pack('=%df' % len(float_samples), *float_samples)
            await websocket.send(binary_data)
            logging.info("Float32 audio sent successfully.")
        except Exception as e:
            logging.error(f"Error in sending audio: {str(e)}")
            # Send error to client
            await websocket.send(text)  # Fallback to sending text

    async def coquiTTS(self, websocket, text):
        try:
            # text = re.suba(r'[^A-Za-z0-9 \s]', '', text)
            output_audio = tts.tts(text=text, speed=0.8, energy=1, pitch=1)
            output_audio = np.array(output_audio, dtype=np.float32)
            await websocket.send(output_audio.tobytes())  # Send audio data to client
            logging.info("TTS response sent successfully.")
        except Exception as e:
            logging.error(f"Error in TTS processing: {str(e)}")

    async def coquiTTS_custom(websocket, text):
        try:
            text = re.sub(r'[^A-Za-z0-9 \s]', '', text)
            output_audio = tts2.tts(text=text, speed=1.2, language='en', speaker_wav=sample_audio)
            output_audio = np.array(output_audio, dtype=np.float32)
            await websocket.send(output_audio.tobytes())  # Send audio data to client
            logging.info("TTS response sent successfully.")
        except Exception as e:
            logging.error(f"Error in TTS processing: {str(e)}")


class Speech_to_text:
    async def process_text(self, websocket, text):
        if text:
            logging.info(f"Received text: {text}")
            try:
                text = "Prompt: Answer in 30 words only for : " + text
                response = GenerateResponse().response_claude(text)
                logging.info(f"Response: {response}")
                await Text_to_Speech().coquiTTS(websocket, response)
                # await Text_to_Speech().googleTTS(websocket, response)
            except Exception as e:
                logging.error(f"Error processing text: {str(e)}")
                await websocket.send("Error processing your request.".encode())

    # WebSocket handler for text input
    async def handle_text(self, websocket):
        logging.info("New client connected.")
        text="Generate a brief intro about yourself, duplex builders and the properties for the user."
        # global greeted
        greeted = False
        flag = 1
        while True:
            logging.info("Entered the while loop.")
            try:
                if flag and not greeted:
                    greeted = True
                    await self.process_text(websocket, text)
                text = await websocket.recv()
                if text=="conversation has ended":
                    logging.info("Connection Terminated.")
                    break
                if text=="INITIAL_CONNECTION":
                    continue
                await self.process_text(websocket, text)
            except websockets.exceptions.ConnectionClosed:
                logging.info("Client disconnected.")
                break
            except Exception as e:
                logging.error(f"WebSocket error: {str(e)}")
                break
    
    async def google_speech_recognizer(self, websocket):
        recognizer = sr.Recognizer()
        while True:
            with sr.Microphone() as source:
                # Adjust for ambient noise and record audio
                recognizer.adjust_for_ambient_noise(source)
                audio = recognizer.listen(source)
                try:
                    # Recognize speech using Google Speech Recognition
                    text = recognizer.recognize_google(audio)
                except Exception as e:
                    text=""
                await self.process_text(text)


async def main():
    start_server = await websockets.serve(Speech_to_text().handle_text, "0.0.0.0", 8765)
    logging.info("WebSocket server started on ws://0.0.0.0:8765")
    await start_server.wait_closed()
    logging.info("Connection Terminated.")

if __name__ == "__main__":
    logging.info("AI Caller is running.")
    print("AI Caller is running.")
    asyncio.run(main())
