import asyncio
import websockets
import logging
import numpy as np
from TTS.api import TTS
import re
import os
import json
import boto3
from dotenv import load_dotenv
import io
import pygame
import time
from gtts import gTTS
from pydub import AudioSegment
import struct
from google.cloud import texttospeech
from google import genai

load_dotenv()
log_file=os.getenv("LOG_FILE")
logging.basicConfig(filename=log_file, level=logging.INFO, 
                    format='%(asctime)s - %(levelname)s - %(message)s', filemode='w', force=True)
logging.info("Initializing AI Caller...")

class GenerateResponse:
    def __init__(self):
        self.client_google = genai.Client(api_key=os.getenv("GOOGLE_GENAI_API_KEY"))
        self.client_meta = boto3.client('bedrock-runtime', region_name='ap-south-1')
        self.model_id_meta = "meta.llama3-70b-instruct-v1:0"
        
        self.client_claude = boto3.client(
            'bedrock-runtime',
            region_name='ap-south-1',
            aws_secret_access_key=os.getenv('AWS_SECRET_ACCESS_KEY_CLAUDE'),
            aws_access_key_id=os.getenv('AWS_ACCESS_KEY_ID_CLAUDE')
        )
        self.talk_file = os.getenv("PREV_REPLY")
        self.model_id_claude = "arn:aws:bedrock:ap-south-1:144023344931:inference-profile/apac.anthropic.claude-3-5-sonnet-20240620-v1:0"
        self.data = self.load_data()
        self.prev_talk = self.get_last_two_queries()
        self.context="""
            You are Eva, an AI assistant for Duplex Builders, but you must act like a human so that the user does not realize you are an AI. Generate responses as if you are a human and not an AI. Do not introduce yourself unless asked by the user.
            The conversation will begin with two dialogs provided to you:
            "Am I talking with {} {}"
            The response from the user.
            Based on these dialogs, proceed as follows:
            If the user confirms they are the above mentioned user, respond with "Hello {} {}, how are you doing?" only.
            else apologize to the user for any inconvience caused and thank him for sparing his time for the call
            If the user responds negatively to the query "how are you doing?", encourage them with empathy (e.g., "I am sorry to hear that. I hope things get better soon.") only and then ask if it is a good time to talk or not.
            elif the user responds positively to the query , acknowledge it briefly (e.g., "Great!") and ask, "Is this a good time to talk?"
            If the user says something like "No, it is not a good time" then suggest reconnecting later (e.g., "Sure, when would be a convenient time for you?").
            elif the user confirms "it is a good time", then Thank the user and Generate a brief introduction about yourself, duplex builders and the properties for the user.
            After the introduction, ask about the user's interests (e.g., "Are you looking for a property to buy or rent? Or would you like to know more about our offerings?").
            Proceed with the conversation based on the user's responses. Try to persuade them to consider buying or renting properties by highlighting benefits, but do not overwhelm them with information unless they specifically ask for details.
            If the user wants to talk to a human agent, provide the contact details of a human agent. The contact number is Nine Zero One Two Three Four Five Six Seven Eight.
            Answer the user briefly unless they ask you to explain further or be specific. Do not provide all the information about the property, such as amenities and features, unless explicitly asked by the user.
            If the property is not available at the location mentioned by the user, respond with "Currently, at this location, they do not have any property."
            Maintain the flow of the conversation based on the previous reply generated by you and the data provided.
            stirctly adhere to this script.
            Here is the data that you have: {}
            Here is the previous dialogues between you and user: {}
        """
        self.question_template = """
        Generate a response based on the information available in Context following response from user: {}
        """
    
    def load_data(self):
        file_path = os.getenv('DATA_FILE')
        with open(file_path,'r') as file:
            data=file.read()
            return data
    
    
    def save_conversation(self, query, response):
        with open(self.talk_file, 'a') as file:
                file.write(f"Query: {query}\nResponse: {response}\n")
    
    def delete_conversation(self):
        with open(self.talk_file, 'w') as file:
                pass

    def get_last_two_queries(self):
        with open(self.talk_file, "r", encoding="utf-8") as file:
            lines = file.readlines()
        # Extract queries and responses
        queries_responses = []
        query, response = None, None
        for line in lines:
            if line.startswith("Query: "):
                query = line.strip()
            elif line.startswith("Response: "):
                response = line.strip()
                if query and response:
                    queries_responses.append((query, response))
        # Get the last two query-response pairs
        last_two = queries_responses[-4:] if len(queries_responses) >= 2 else queries_responses
        return last_two


    def response_claude(self, query, title, name):
        question = self.question_template.format(query)
        message = question + self.context.format(title, name, title, name, self.data, self.prev_talk)
        input_payload = [
            {
                "role": "user",
                "content": [
                    {"text": message},
                ],
            }
        ]
        response_claude = self.client_claude.converse(
            modelId=self.model_id_claude,
            messages=input_payload,
        )    
        response = response_claude['output']['message']['content'][0]['text']
        self.save_conversation(query, response)
        return response
    

    def response_meta(self, query, title, name):
        question = self.question_template.format(query)
        input_payload = {"prompt": question + "\n\n" + self.context.format(title, name, title, name, self.data, self.prev_talk)}
        response = self.client_meta.invoke_model(
            modelId=self.model_id_meta,
            contentType='application/json',
            accept='application/json',
            body=json.dumps(input_payload)
        )
        response_body = response['body'].read().decode('utf-8')
        result = json.loads(response_body)
        return result.get("generation", "No response generated")
    
    def response_google_genai(self, query, title, name):
        question = self.question_template.format(query)
        message = question + self.context.format(title, name, title, name, self.data, self.prev_talk)
        response = self.client_google.models.generate_content(
            model='gemini-2.0-flash',
            contents=message
        )
        self.save_conversation(query, response.text)
        return response.text


class Text_to_Speech:
    def __init__(self):
        self.polly_client = boto3.client('polly', region_name='ap-south-1')

    async def googleTTS(self, websocket, text):
        try:
            gtts = gTTS(text=text, lang='en')
            mp3_fp = io.BytesIO()
            gtts.write_to_fp(mp3_fp)
            mp3_fp.seek(0)
            audio = AudioSegment.from_mp3(mp3_fp)
            audio = audio.set_channels(1)
            audio = audio.set_frame_rate(22050)
            samples = audio.get_array_of_samples()
            max_value = float(max(abs(sample) for sample in samples))
            float_samples = [float(sample) / max_value for sample in samples]
            binary_data = struct.pack('=%df' % len(float_samples), *float_samples)
            await websocket.send(binary_data)
            logging.info("Float32 audio sent successfully.")
        except Exception as e:
            logging.error(f"Error in sending audio: {str(e)}")
            # Send error to client
            await websocket.send(text)  # Fallback to sending text
    
    async def polly_tts(self, websocket, text, speaker):
        """Convert text to speech using Amazon Polly and play it in real-time."""
        if speaker=='Kajal':
            engine='neural'
        else:
            engine='standard'
        try:
            response = self.polly_client.synthesize_speech(
                TextType='text',  # Use 'text' for plain text (use 'ssml' for SSML)
                Text=text,
                Engine=engine,  #standard(Aditi, Raveena) or neural(Kajal)
                LanguageCode="en-IN",  # Aditi supports only en-IN
                OutputFormat='mp3',  # Use mp3 for audio output
                VoiceId=speaker
            )
            logging.info(f"Response Metadata: {response['ResponseMetadata']}")
            logging.info(f"Content Type: {response['ContentType']}")
            logging.info(f"Request Characters: {response['RequestCharacters']}")
            audio_data = response['AudioStream'].read()
            await websocket.send(audio_data)  # Send raw MP3 bytes
            logging.info("polly_TTS response sent successfully.")
        except Exception as e:
            logging.info(f"Error in Amazon Polly TTS: {e}")
    
    async def google_cloud_tts(self, websocket, text, speaker):
        credentials = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
        try:
            client = texttospeech.TextToSpeechClient()
            synthesis_input = texttospeech.SynthesisInput(text=text)
            voice = texttospeech.VoiceSelectionParams(
                language_code="en-IN",
                name=speaker
            )
            audio_config = texttospeech.AudioConfig(
                audio_encoding=texttospeech.AudioEncoding.MP3,
                effects_profile_id=['small-bluetooth-speaker-class-device'],
                speaking_rate=1,
            )
            response = client.synthesize_speech(
                input=synthesis_input,
                voice=voice,
                audio_config=audio_config
            )
            await websocket.send(response.audio_content)  # Send raw MP3 bytes
            logging.info("google_cloud_tts response sent successfully.")
        except Exception as e:
            logging.info(f"Error in Google Cloud TTS: {e}")


class Speech_to_text:
    def __init__(self):
        self.tts = Text_to_Speech()

    async def process_text(self, websocket, text, provider, speaker, title, name):
        if text:
            logging.info(f"Received text: {text}")
            try:
                text = "Prompt: Answer in 30 words only for : " + text
                try:
                    response = GenerateResponse().response_google_genai(text, title, name)
                except Exception as e:
                    logging.error(f"Error {e} while generating response with Google GenAi, trying using Claude")
                    response = GenerateResponse().response_claude(text, title, name)
                logging.info(f"Response: {response}")
                if provider == 'google':
                    await self.tts.google_cloud_tts(websocket, response, speaker)
                elif provider == 'amazon':
                    await self.tts.polly_tts(websocket, response, speaker)
            except Exception as e:
                logging.error(f"Error processing text: {str(e)}")
                await websocket.send("Error processing your request.".encode())

    # WebSocket handler for text input
    async def handle_text(self, websocket):
        logging.info("New client connected.")
        greeted = False
        tts = self.tts
        try:
            # Receive initial data from the client
            data = await websocket.recv()
            data = json.loads(data)
            user = data.get('username')
            title = data.get('title')
            provider = data.get('provider').lower()
            speaker = data.get('voice')

            # Step 1: Initial Greeting
            text_init = f"Hello, am I speaking with {title} {user}?"
            time.sleep(3)
            if provider == 'google':
                await tts.google_cloud_tts(websocket, text_init, speaker)
            elif provider == 'amazon':
                await tts.polly_tts(websocket, text_init, speaker)

            while True:
                logging.info("Entered the while loop.")
                try:
                    text = await websocket.recv()
                    if text=="conversation has ended":
                        logging.info("Connection Terminated.")
                        GenerateResponse().delete_conversation()
                        break
                    if text=="INITIAL_CONNECTION":
                        continue
                    await self.process_text(websocket, text, provider, speaker, title, user)
                except websockets.exceptions.ConnectionClosed:
                    logging.info("Client disconnected.")
                    break
                except Exception as e:
                    logging.error(f"WebSocket error: {str(e)}")
                    break
        except websockets.exceptions.ConnectionClosed:
            logging.info("Client disconnected.")
        except Exception as e:
            logging.error(f"An Error Occurred: {e}")


async def main():
    start_server = await websockets.serve(Speech_to_text().handle_text, "0.0.0.0", 8765)
    logging.info("WebSocket server started on ws://0.0.0.0:8765")
    await start_server.wait_closed()
    logging.info("Connection Terminated.")

if __name__ == "__main__":
    logging.info("AI Caller is running.")
    print("AI Caller is running.")
    asyncio.run(main())
